### ISSUE TITLE
Separate Caddy module from certmagic Storage implementation

### ISSUE THREAD

**Issue by shrink** [grafana/certmagic-gcs#150]
CertMagic does not have a dependency on Caddy so it should be possible to use `certmagic-gcs` without Caddy. Unfortunately because of [`init()`](https://github.com/grafana/certmagic-gcs/blob/main/module.go#L30-L32) it is not possible to use this package outside of Caddy. Separating out the CertMagic storage implementation from the Caddy module would be very helpful for non-Caddy use-cases.

Thank you :)

**Comment by hairyhenderson** [comment]
Thanks for the suggestion (and the PR) @shrink - this seems like a useful change!
