### ISSUE TITLE
Is this stable?

### ISSUE THREAD

**Issue by francislavoie** [grafana/certmagic-gcs#5]
I just wanted to poke my head in and say hi!

If you think this implementation is stable, you could register it on the https://caddyserver.com website, which will make it appear in https://caddyserver.com/docs/json/storage/ as one of the supported storage plugins for Caddy. It's one of the best ways for users to discover this plugin.

**Comment by chaudyg** [comment]
Thanks for raising this issue🙇 !

We are still testing this implementation. We will register it to caddy storage plugins when we are done experimenting 👍 .

**Comment by thomasjahoda** [comment]
Any updates?

**Comment by hairyhenderson** [comment]
I don't know how "stable" we want to consider this, but we've been using it in production for a while now with no obvious issues.

@chaudyg do you want to register this?

**Comment by chaudyg** [comment]
Yes. Let's register it. What's the process for registration (couldn't find it on the website)?

**Comment by francislavoie** [comment]
You need to make an account (button in the top-right nav), then claim the module path.

**Comment by hairyhenderson** [comment]
@chaudyg I have an account already - want me to register it?

**Comment by hairyhenderson** [comment]
Ok, I've registered it now!

**Comment by hairyhenderson** [comment]
And here it is: https://caddyserver.com/docs/json/storage/gcs/!

**Comment by hairyhenderson** [comment]
I think we can close this issue, now that it's registered 😉
