### ISSUE TITLE
Credentials for GCS

### ISSUE THREAD

**Issue by nerdeveloper** [grafana/certmagic-gcs#69]
Hello there, 

I want to use this tool to configure GCS; I am a noob but isn't there supposed to be a way to auth on gcloud before it can see the bucket on google cloud or am I supposed to create a public bucket.

Kindly assist.

**Comment by hairyhenderson** [comment]
Using Application Default Credentials (ADC) is the simplest approach: https://cloud.google.com/docs/authentication/provide-credentials-adc
