### ISSUE TITLE
Add a license ? :) 

### ISSUE THREAD

**Issue by desimone** [grafana/certmagic-gcs#92]
## Got

No license. Since the code is unlicensed, we (and others I would assume) would not be able to use the code. 

## Want

A license. Ideally something FOSS compatible. May I suggest, Apache 2, BSD, or MIT.

Thanks for the great package.

**Comment by hairyhenderson** [comment]
Thanks for filing this @desimone - indeed we should have an explicit license. We'll discuss it internally!
